# Generated by Django 4.2.11 on 2025-11-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ManyToManyField(to='Tienda.categoriap'),
        ),
    ]
