# Generated by Django 4.2.11 on 2025-11-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fotoP',
            field=models.ImageField(blank=True, null=True, upload_to='tienda'),
        ),
    ]
