# Generated by Django 4.2.11 on 2025-11-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_alter_producto_fotop'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponivilidad',
            field=models.BooleanField(default=True),
        ),
    ]
